# -*- coding: utf-8 -*-
"""Kriminalitaet NY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13kU0F0QAWpTQml4rpwcWNsWl8m79TNXe
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv("/content/drive/MyDrive/NYPD_Complaint_Data_Historic_sampled.csv.gz",compression="gzip")

"""# DATA CLEANING

"""

df_clean = df.drop(columns = ["STATION_NAME"])
df_clean = df_clean.drop(columns = ["TRANSIT_DISTRICT"])
df_clean = df_clean[~df_clean.isin(['(null)'])]
df_clean = df_clean[~df_clean.isin(['UNKNOWN'])]
df_clean["SUSP_SEX"] = df_clean['SUSP_SEX'].fillna('U')
df_clean["VIC_RACE"] = df_clean['VIC_RACE'].fillna("U")
df_clean["VIC_AGE_GROUP"] = df_clean['VIC_AGE_GROUP'].fillna(method = "ffill")
df_clean["SUSP_RACE"] = df_clean['SUSP_RACE'].fillna("U")
df_clean["SUSP_AGE_GROUP"] = df_clean['SUSP_AGE_GROUP'].fillna("0")
df_clean = df_clean.drop(columns = ["HADEVELOPT"])
df_clean = df_clean.drop(columns = ["HOUSING_PSA"])
df_clean['PATROL_BORO'] = df_clean['PATROL_BORO'].dropna()
df_clean = df_clean.fillna("U")

# NAs were not removed as too much data would be lost.
# Instead, they were replaced with 'U' for Unknown to retain the data in the remaining columns.
# Other columns were removed because there was so much unknown data that they were not usable.

"""# First Graphical Representation"""

df_clean['CMPLNT_FR_DT'] = pd.to_datetime(df_clean['CMPLNT_FR_DT'], format='%m/%d/%Y')
df_clean['Year'] = df_clean["CMPLNT_FR_DT"].dt.year

g1 = sns.catplot(
    data = df_clean ,
    kind = "count",
    x = "Year",
    hue = "Year",
    palette = "colorblind"

)
g1.fig.suptitle("Crimes in New York per Year")
g1.set(xlabel = "Years from 2020 till 2023",
       ylabel = "The number of crimes per year")
plt.show()

"""This chart shows how the total number of crimes in New York has changed over the years. There is a noticeable increase from 2021 to 2022. This could have various reasons. It may primarily be due to the easing of restrictions after the COVID-19 pandemic, which led to more people being outdoors, resulting in more crimes.

# Second Graphical Representation
"""

g2 = sns.catplot(
    data = df_clean,
    kind = "count",
    stat = "percent",
    x = "PATROL_BORO",
    hue = "PATROL_BORO"
)
plt.xticks(rotation=80)
g2.fig.suptitle("Crimes per Patrol Boro")
g2.set(xlabel = "Patrol Boro",
       ylabel = "Percentage of committed crimes")
plt.show()

"""This chart shows which district has the most crimes committed. What stands out is the Bronx, where by far the most crimes occur. This is likely because the Bronx is one of the poorest neighborhoods, which often leads to higher crime rates.

# Third Graphical Representation
"""

df_Susp_race = df_clean[~df_clean["SUSP_RACE"].isin(["U"])]
g3 = sns.catplot(
    data = df_Susp_race,
    kind = "count",
    stat = "percent",
    x = "SUSP_RACE",
    hue = "SUSP_RACE"
)
plt.xticks(rotation=80)
g3.fig.suptitle("Race of the suspected offenders")
g3.set(xlabel = "Race of the Suspected People",
       ylabel = "Percentage of committed crimes")
plt.show()

"""This chart shows the race of the suspected individuals. What stands out is that most of the suspects are Black. This is mainly due to the fact that many of these individuals live in impoverished neighborhoods and often resort to crime as a means of obtaining money.

# Fourth Graphical Representation
"""

g4 = sns.catplot(
    data = df_clean,
    kind = "count",
    stat = "percent",
    x = "SUSP_SEX",
    hue = "VIC_SEX"
)
g4.fig.suptitle("Sex of the Suspected People and Victims")
g4.set(xlabel = "Sex of the Suspected People",
       ylabel = "Percentage of committed crimes")
plt.show()

"""This chart shows the gender of the suspected individuals. What stands out is that most crimes are committed against women. The majority of these crimes are committed by men against women. This is mainly because men are often physically stronger than women, and this is exploited in such situations.

# Fifth Graphical Representation
"""

Age_GROUP = ['<18', '18-25', '25-44', '45-64', '65+']
df_age = df_clean[df_clean['SUSP_AGE_GROUP'].isin(Age_GROUP)]

g5 = sns.catplot(
    data = df_age,
    kind = "count",
    stat = "percent",
    x = "SUSP_AGE_GROUP",
    hue = "SUSP_AGE_GROUP"
)
g5.fig.suptitle("Age of the suspected offenders")
g5.set(xlabel = "Age of the Suspected People",
       ylabel = "Percentage of committed crimes")
plt.show()

"""This chart shows the proportion of different age groups involved in crime. Especially individuals aged 25-44 account for the largest share, with approximately 70% of total crimes. However, individuals aged 45-64 also represent a significant portion, accounting for about 25%.

#Sixth Graphical Representation
"""

df_Vic_race = df_clean[~df_clean["VIC_RACE"].isin(["U"])]
g6 = sns.catplot(
    data = df_Vic_race,
    kind = "count",
    stat = "percent",
    x = "VIC_RACE",
    hue = "VIC_RACE"
)
plt.xticks(rotation=80)
g6.fig.suptitle("Race of the Victims")
g6.set(xlabel = "Race of the Victims",
       ylabel = "Percentage of committed crimes")
plt.show()

"""This chart shows the race of the victims of crimes. What stands out is the high proportion of Black individuals who suffer from crimes, as well as the relatively high percentage of Asian individuals. While the proportion of Asians among the suspects is very low, the percentage of Asian victims is quite high. This could be because Asians, on average, tend to be smaller and more fragile than most people, making them more likely to fall victim to crimes rather than committing them.



"""